services:
  op7nexo-front:
    image: op7nexo-front:latest
    container_name: op7nexo-front
    restart: unless-stopped
    ports:
      - "3000:3000"
    networks:
      - traefik-public
    environment:
      - NODE_ENV=production
      - PORT=3000
      - NEXT_PUBLIC_API_URL=http://op7nexo-api:8000
      - NEXT_PUBLIC_APP_URL=https://nexo.op7franquia.com.br
      - JWT_SECRET=0085aed4be44de469e3fdd6cb8039bddf744927c1dfbf0099474dea450f6c2c9
    labels:
      - traefik.enable=true
      - traefik.http.routers.op7nexo-front.rule=Host(`nexo.op7franquia.com.br`)
      - traefik.http.routers.op7nexo-front.entrypoints=websecure
      - traefik.http.routers.op7nexo-front.tls.certresolver=letsencrypt
      - traefik.http.routers.op7nexo-front.service=op7nexo-front
      - traefik.http.services.op7nexo-front.loadbalancer.server.port=3000
      - traefik.http.services.op7nexo-front.loadbalancer.passHostHeader=true

networks:
  traefik-public:
    external: true
    name: traefik-public
